### ISSUE TITLE
How to work with cluster that has two load balancers.

### ISSUE THREAD

**Issue by royipressburger** [neo4j/neo4j-javascript-driver#181]
Hi all

I was wondering how to work with the drive if my Neo4j has 2 load balancers.

According to Neo4j documentation, when starting a cluster the best way to work with it is by sending all the write queries to the master and the reading to the slaves.
Because of that It sounds reasonable to create a cluster with two load balancers:
1. for the writers nodes( the master )
2. for the slaves

Does the driver knows how to handle this case?
How does the new routing feature (`"bolt+routhing://localhost"`) help me with this issue?

Thanks ahead :)

**Comment by lutovich** [comment]
Hi @royipressburger,

There are two clustering options in neo4j 3.1:
 1) Highly Available cluster (HA) https://neo4j.com/docs/operations-manual/current/clustering/high-availability/
 2) Causal Cluster (CC) https://neo4j.com/docs/operations-manual/current/clustering/causal-clustering/

In HA you can write to both slave and master but effectively all writes will end up on master because slaves basically send write transactions to master to commit. So I think it makes sense to a single load balancer with two open ports - one for writes proxying master and one for reads proxying slaves. App can have two drivers corresponding to those ports. More about this here: https://neo4j.com/docs/operations-manual/current/clustering/high-availability/haproxy/.

In CC you can only write to leader and read from followers and read replicas. Scheme `bolt+routing` only supports 3.1+ CC clusters. It should be enough to have a single driver here. It'll do loadbalancing itself. A bit more about this here: https://neo4j.com/docs/developer-manual/current/drivers/configure-connect/.

I'd suggest using CC cluster with `bolt+routing` driver. Load balancer could probably be omitted in this case.

Please let us know if you have any other questions :)

**Comment by royipressburger** [comment]
@lutovich Hi and thanks for the response..

I Must say that I didn't really get the difference between the two.
It sounds like `leader (on CC) == master (on HA)` and `followers (on CC) == slaves (on HA)`
In CC mode: do i still need to write to the leader?

I probably miss something.

**Comment by lutovich** [comment]
@royipressburger difference in terminology comes from different underlying consensus algorithm. What you say is true as the high level overview. HA does not have a notion of read replicas. In CC you can only write to leader and read from followers and read replicas.

Please check "Architecture" section of the manual for HA and CC, it has more details and better description than I can give:
https://neo4j.com/docs/operations-manual/current/clustering/high-availability/architecture/
https://neo4j.com/docs/operations-manual/current/clustering/causal-clustering/introduction/

Again, I'd suggest using CC + `bolt+routing` driver. It'll handle loadbalancing business.

**Comment by royipressburger** [comment]
@lutovich If using `bolt+routing`, I can just give it one of the nodes url? no need to put all of them behind LB and use the load balancer url, right?

**Comment by lutovich** [comment]
@royipressburger correct, it just requires a single core(leader or follower, not read replica) member uri.

**Comment by royipressburger** [comment]
@lutovich Sounds Good Thanks!

**Comment by zhenlineo** [comment]
We are closing this issue now. Pls contract us if you get any other problems.
Cheers,
Zhen
