### ISSUE TITLE
ImpermanentGraphDatabase

### ISSUE THREAD

**Issue by terencechow** [neo4j/neo4j-javascript-driver#211]
Is there a way to use the `ImpermanentGraphDatabase` with this driver? I would like to open a session that uses the `ImpermanentGraphDatabase` when doing tests as opposed to deleting the entire graph whenever i'm done.

**Comment by lutovich** [comment]
Hi @terencechow,

Could you please explain a little bit more what you would like to achieve and what test setup do you have?

It is not possible to start Neo4j database directly from the driver, so you have to have some sort of command line tool that starts database before test and stops it after test. We have thing like this in the JS driver, it is `neokit` submodule and gulp uses it: https://github.com/neo4j/neo4j-javascript-driver/blob/1.1.1/gulpfile.babel.js#L246-L267.
For non-impermanent database I'd recommend using https://github.com/neo4j-contrib/boltkit command line utility instead of `neokit`. For `ImpermanentGraphDatabase` there should be some tool in Java that starts it and then JS app can use such tool for testing. I do not think such tool exists right now.

Thanks!

**Comment by terencechow** [comment]
In mongodb I set my tests to `use test_db` which allows me to create and delete a brand new db for the purposes of testing. This doesn't affect my local dev database because i `use dev_db` when developing locally. Basically this means I can namespace my databases in mongo.

Perhaps i'm misunderstanding how testing is generally done in neo4j but it seems to me that there is no 'namespacing' of databases in neo4j. Hence I thought the ability to switch to `ImpermanentGraphDatabase` would allow me to keep my local dev database intact.

You can imagine that if I am making an app, having some prepopulated data is useful since empty results from the db will generally display a message in my app that says "Nothing to display"...

Hence it would be nice to have my `npm run test` not delete the dev db in addition to the test db. As an aside, I could theoretically keep track of every node / relationship that is created in an `npm run test`, but obviously that is less than ideal and error prone.

How do you do testing / recommend testing neo4j in javascript? If there is nothing I can do besides scripts then I'll write a script that prepopulates neo4j for development but any guidance on recommended practices is appreciated. thanks!

**Comment by lutovich** [comment]
Hi @terencechow,

I do not think there exists a solution with `ImpermanentGraphDatabase` because it is only an internal testing utility and can only by used if pulled in as a maven dependency in java. You could probably use [boltkit](https://github.com/neo4j-contrib/boltkit) to start/stop separate test-only neo4j database locally in `beforeEach`/`afterEach`. This is basically what we do in integration tests.

Is it ok for you to use 'real' database with boltkit? It should probably have the same effect as `ImpermanentGraphDatabase` except maybe a bit slower.

**Comment by zhenlineo** [comment]
Hi @terencechow 
This is not currently planed and it is not part of the driver work scope. So we are closing this issue.
Pls use boltkit to start a external server for testing.

Thanks.
