### ISSUE TITLE
ES6 promises vs. bluebird

### ISSUE THREAD

**Issue by ekkis** [neo4j/neo4j-javascript-driver#214]
I'm upgrading a project from 2.3 whereby I had wrapped functionality to return promises using the excellent Bluebird library.  I see that the new 3.1 drivers return ES6 promises and I realize I can wrap them in Bluebird but it would be much better if the library provided a mechanism for the caller to indicate the promise library to use

**Comment by brian-gates** [comment]
I disagree.  This driver should not be concerned with Bluebird unless it is an internal dependency.  It's trivial to wrap and would only add unnecessary complexity for the driver itself.

**Comment by lutovich** [comment]
Hello @ekkis, @brian-gates, thanks for your input.

We've honestly never considered pluggable promise library and I'm not really sure how this is going to work with our existing `babel-runtime`. Are there any examples of libraries that support pluggable promises?

I tend to agree with @brian-gates because this might indeed bring additional complexity.

**Comment by ekkis** [comment]
yes, there are other libs out there that allow configuring them for which promise library to use e.g. http://mongoosejs.com/docs/promises.html#plugging-in-your-own-promises-library

**Comment by technige** [comment]
Thank you for the suggestion but at this time, we feel this would increase the complexity of the code. If we see a greater desire for this feature in future, we will happily reconsider.
