### ISSUE TITLE
Documentation clarification about database version

### ISSUE THREAD

**Issue by canibanoglu** [neo4j/neo4j-javascript-driver#24]
Hello,

I installed the neo4j-driver with `npm install neo4j-driver` but I have been unsuccessful in getting any response back from the server. I later discovered that this was due to the fact that the Neo4j version was 3.0.0-M02. Everything seems to work just fine after installing 3.0.0-M01 on the server. 

It would be very nice to see this in the documentation so that people don't struggle to find what the problem is. 

One thing that bugs me is that the included tests seem to pass when I run them after `cd`ing into `node_modules/neo4j-driver`. I can't for the life of me explain why that would be.

This seems to be a problem with the Python driver as well, should I open an issue over that repo as well?

I would be more than happy to submit a PR for this, if that suits you.

Kind regards,

Can

**Comment by jakewins** [comment]
This is actually a problem for all the drivers currently - we don't yet have a first stable release of the Bolt database protocol, meaning the drivers break when the current unstable version of the protocol changes in the main product :( 

This is going to be resolved as soon as the first stable protocol version, V1, is released with Neo4j 3.0.0 GA. 

The tests are passing because they are using the nightly product builds, available here: http://alpha.neohq.net/

If you want to add a note to the README of the drivers we have in a PR saying that using the latest version of these drivers currently and temporarily requires using the nightly Neo4j builds, I'd be more than happy to merge that!

**Comment by jakewins** [comment]
We've now reached Release Candidate stability for the Bolt protocol and for all the drivers, meaning this should no longer be an issue as long as you're using >= RC1
