### ISSUE TITLE
Neo4j URL with context path ?

### ISSUE THREAD

**Issue by jlafourc** [neo4j/neo4j-javascript-driver#325]
Hi,

I'd like to install some simple Neo4j dbs in a Kubernetes cluster. When I use the Neo4j webbrowser to access the DB via bolt, it's a connection from outside the cluster so I have to use websocket protocol to go through the Ingress (LoadBalancer). 

I made some experiments to access the db via bolt through an HAProxy. At the domain level, it's working perfectly:
- bolt://test1.example.org:7687 points to test1 instance
- bolt://test2.example.org:7687 points to test2 instance

All is going through the HAProxy. 

Now, I'd like to have:
- bolt://test.example.org:7687/neo1 points to test1 instance
- bolt://test.example.org:7687/neo2 points to test2 instance

But it seems like the driver swallows the context path part. In the end both cases try to connect to bolt://test.example.org:7687 (which gives me 503 errors from HAProxy). 

I'd like to know if there's anything I can do about that ? 

Thanks

Julien

**Comment by lutovich** [comment]
Hi @jlafourc,

Driver constructs a url for `WebSocket` using only hostname and port. I guess it could include things like query path and parameters as well. However, this would not work in NodeJS version because simple socket connection is used there. Right now we consider the URI path reserved for future use. It could in future be used to locate graph, shard, etc. Unfortunately I'd consider this issue a "won't fix".

Am I right that you are deliberately not using Causal Cluster with `bolt+routing` scheme and driver side load balancing?

**Comment by jlafourc** [comment]
Hi @lutovich,

Thanks for your quick answer. I totally undenstand. I guess I'll have to go with the port solution (which should be acceptable)

The bolt+routing seems to match other use cases. I don't cluster anything at moment. My intentions here are just to use the browser  to access neo4j databases that are inside my cluster. 

Thx 

Julien

**Comment by lutovich** [comment]
@jlafourc okey, I understand. Your databases basically represent completely different graphs. I will close this issue now. Please feel free to reopen if needed.
