### ISSUE TITLE
Set transaction timeout

### ISSUE THREAD

**Issue by will3942** [neo4j/neo4j-javascript-driver#331]
How do i set the timeout of a transaction I can't see how to do it in the documentation:

```

The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. The transaction has not completed within the specified timeout. You may want to retry with a longer timeout.
```

**Comment by lutovich** [comment]
Hi @will3942,

Currently there is no way to override transaction timeout from the driver. It is only possible to configure timeout in the database. See [this docs section](https://neo4j.com/docs/operations-manual/current/monitoring/query-management/#transaction-timeout) for more details.

Hope this helps.

**Comment by will3942** [comment]
Thankyou!

**Comment by Gudahtt** [comment]
This would still be useful to configure at the driver level though. I have a case now where I want a short timeout for one client and a long timeout for another.

The workaround we're considering is to track the timeout at the application level and call `rollback` on the transaction if it times out. Support from the driver would be preferred though.

**Comment by adarsh-sgh** [comment]
https://github.com/neo4j/neo4j-javascript-driver/blob/ae16fa3be143207eb222aa4bd3c556360739c053/packages/core/src/session.ts#L46-L48
It looks like now we can set the timeout in the `TransactionConfig` object passed to `session.run` 
but it's not clear what is the unit of the time here ? is it milliseonds or something else ? 

Also wanted to know if there's a way to set `dbms.lock.acquisition.timeout` ? 
since the neo4j documentation says 

> It’s highly recommended that when you set the transaction timeout that you set the lock acquisition timeout as well.

 https://neo4j.com/developer/kb/understanding-transaction-and-lock-timeouts/

**Comment by adarsh-sgh** [comment]
@bigmontz @lutovich  can you please help with my questions above ? 
We can then add it as a comment in the source code or readme.
