### ISSUE TITLE
Create multiple sessions or reuse them for different queries?

### ISSUE THREAD

**Issue by jyounus** [neo4j/neo4j-javascript-driver#334]
Hey there,

This is more of a questions rather than issue. What's the best practise regarding using/creating session objects?

The readme says "Create a session to run Cypher statements in. Note: Always make sure to close sessions when you are done using them!"

My question is, if I have to run multiple queries, should I create individual sessions OR should I create 1 session and reuse that for all of the queries that I need to run? 

Does it even matter? Does this have any sort of performance impacts? Would it run fine if say I run query 1 and then using the same session I run query 2 and it fails? Would the changes from query 1 still be applied or would the whole operation fail and revert to the original state it was before query 1 was executed?

Hope this makes sense, maybe I'm just overthinking it here and it doesn't even matter. But I'm just thinking about a theoretical use case here were this is part of an API call which 100s (or more) of users are calling per minute etc.

**Comment by lutovich** [comment]
Hi @jyounus,

Session objects are very lightweight. Each session will acquire connection from the connection pool when needed and release it as soon as possible (after query failed, result is fully fetched or transaction is committed/rolled back).

Queries in a single session will get executed sequentially. They could potentially reuse the same network connection. Queries in different sessions can be executed in parallel by the database, because they can be sent through separate connections.

It is recommended for sessions to be short-lived. One session can definitely be created per-query when parallelism is desirable and smth like `Promise.all()` is used.

Hope this helps.

**Comment by jyounus** [comment]
Perfect, that makes sense. I'm currently using them on a per-query basis, so no point refactoring/changing it since it won't really change much. 

Thanks a lot, @lutovich!
