### ISSUE TITLE
BigInt support

### ISSUE THREAD

**Issue by jekel1818** [neo4j/neo4j-javascript-driver#409]
Hi!

This is more a question than a real issue.

I wanted to known if there is any plan to add support for the new javascript BigInt type since there are now supported by Nodejs. I think that the BigInt primitive would solve the problem of javascript Number primitive being limited to 2**53 bit. Since there is already an option to return a Number primitive

`{disableLosslessIntegers: true}`

maybe a similar config could be added to return BigInt? 

Thank a lot.

**Comment by lutovich** [comment]
Hi @jekel1818,

Thanks for raising this issue!

I think `BigInt` can definitely be used by the driver to replace the custom `Integer` type. As you suggest, this should definitely be a config option for now, because not all JS engines support `BigInt`s. Option `disableLosslessIntegers` would still be needed because `BigInt` and `Number` are not fully compatible, so driver can't always return `BitInt`s. For example `BigInt(1) / Number(1)` results in a `TypeError`, as well as `JSON.stringify({v: BigInt(1)})`.

We will discuss support for `BigInt` further. Thanks again!

**Comment by jekel1818** [comment]
All right! Thanks for your answer!
