### ISSUE TITLE
Is it feasible to return better parseable errors on the client?

### ISSUE THREAD

**Issue by purplemana** [neo4j/neo4j-javascript-driver#417]
Errors currently return contextual information as a message, making it difficult to parse and process them on the client, e.g. here's a message depicting unique constraint violation:

    { 
      Neo4jError: Node(40) already exists with label `User` and property `id` = 'test@domain.com'

        at captureStacktrace (/mnt/c/Code/alchemist/node_modules/neo4j-driver/lib/v1/result.js:200:15)
        at new Result (/mnt/c/Code/alchemist/node_modules/neo4j-driver/lib/v1/result.js:73:19)
        at Session._run (/mnt/c/Code/alchemist/node_modules/neo4j-driver/lib/v1/session.js:116:14)
        at Session.run (/mnt/c/Code/alchemist/node_modules/neo4j-driver/lib/v1/session.js:95:19)
        at Neode.cypher (/mnt/c/Code/alchemist/node_modules/neode/build/index.js:366:14)
        at Neode.writeCypher (/mnt/c/Code/alchemist/node_modules/neode/build/index.js:342:23)
        at Builder.execute (/mnt/c/Code/alchemist/node_modules/neode/build/Query/Builder.js:706:40)
        at /mnt/c/Code/alchemist/node_modules/neode/build/Services/Create.js:39:39
        at process._tickCallback (internal/process/next_tick.js:68:7)
        at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
      code: 'Neo.ClientError.Schema.ConstraintValidationFailed',
      name: 'Neo4jError' 
    }

The `code` value `Neo.ClientError.Schema.ConstraintValidationFailed` doesn't indicate _which_ constraint has failed. To do that, one must parse the error message to figure out the various features of the exception, in this case, its a unique constraint on id field.

Returning errors with the raw fields would be helpful to write client parsing logic which is not fragile if the driver changes the error message tomorrow. E.g., in this case:

    { 
      Neo4jError: Node(40) already exists with label `User` and property `id` = 'suk@1.com'

        at captureStacktrace (/mnt/c/Code/alchemist/node_modules/neo4j-driver/lib/v1/result.js:200:15)
        at new Result (/mnt/c/Code/alchemist/node_modules/neo4j-driver/lib/v1/result.js:73:19)
        at Session._run (/mnt/c/Code/alchemist/node_modules/neo4j-driver/lib/v1/session.js:116:14)
        at Session.run (/mnt/c/Code/alchemist/node_modules/neo4j-driver/lib/v1/session.js:95:19)
        at Neode.cypher (/mnt/c/Code/alchemist/node_modules/neode/build/index.js:366:14)
        at Neode.writeCypher (/mnt/c/Code/alchemist/node_modules/neode/build/index.js:342:23)
        at Builder.execute (/mnt/c/Code/alchemist/node_modules/neode/build/Query/Builder.js:706:40)
        at /mnt/c/Code/alchemist/node_modules/neode/build/Services/Create.js:39:39
        at process._tickCallback (internal/process/next_tick.js:68:7)
        at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
      code: 'Neo.ClientError.Schema.ConstraintValidationFailed',
      props: {
        constraint: "unique",
        on: "User",
        assert: "id"
      }
      name: 'Neo4jError' 
    }

**Comment by lutovich** [comment]
Hey @purplemana,

I think this not a bad idea but will be quite hard to implement because those messages originate from Java exceptions in the database. Every place in the database code that throws a user-facing exception would need to create a `props` object and attach it to the thrown exception. Bolt server would then need to forward `props` separately to the driver.

What do you think @nigelsmall?

**Comment by technige** [comment]
My view is that parsing the text from error messages is pretty fragile in the general case. Consider in particular the difficulties in parsing the serialised forms of complex data types, escape characters and internationalised text.

As @lutovich stats, these error messages are generated by the server. As such, they can be very context specific. That makes it hard to produce a meaningful set of extracted data as part of a general purpose solution. That said, you might have some success with a solution very specific to your domain or application, and for a specific version of Neo4j (error message text isn't typically considered part of the public API and therefore isn't protected from change by semantic versioning).

Can I ask _how_ you intend to use the constraint name, etc? Does it affect your code path? If so, why? Are those code paths future-proof? Or is it a case of wanting to bubble information up to the user? In which case, is it simply adding the constraint name to the error message that is important, rather than deconstructing and reconstructing the server error?

**Comment by purplemana** [comment]
@technige As of now the intention is to bubble the information to the user. But it does impact the code path, e.g. there could be several constraints on the model (I have some uniques and some key existences). In case of constraint violations, the details (_which_ field?) part is super important. Some of these constraint errors will simply be asking the user for providing a different input (unique email), some of them could be addressable in the code as well (pad a default missing filed if the record didn't have one).

I can parse messages, but then it'd be great if there's a list of these documented somewhere (Neo4J reference perhaps?).

Thanks @lutovich and @technige for pitching in so fast on this!

**Comment by lutovich** [comment]
@purplemana thanks for raising this issue. Unfortunately, implementing the proposed extension of errors in not quite feasible at the moment. IMHO parsing error messages can be very fragile and it is better to keep track of the label/property in the application code, if possible. For example:

```javascript
async function createNode(driver, label, property, value) {
  const session = driver.session();

  try {
    await session.run(`CREATE (:${label} {${property}: ${value}})`);
  } catch (e) {
    if (e.code === 'Neo.ClientError.Schema.ConstraintValidationFailed') {
      // safe to rely on the status code because it is a stable string
      throw new Error(`Please provide a unique ${property}, value ${value} is already in use`);
    }
    throw e;
  } finally {
    session.close();
  }
}
```

This function relies on the status code, which is stable and backwards compatible. It also keeps track of the label and property and constructs a query dynamically.

Hope this helps!

**Comment by purplemana** [comment]
Thanks @lutovich. I do hope to see more parse-able errors in the roadmap of Neo4J.
