### ISSUE TITLE
ORDER BY placeholder is broken

### ISSUE THREAD

**Issue by ivan-kleshnin** [neo4j/neo4j-javascript-driver#420]
The next snippet:

```js
let records = await req.db.session.run(`
    MATCH (document :Post)
    RETURN document
    ORDER BY document.publishDate DESC
`)
```

produces the following, sorted by `publishDate` field, result:

```
[ {url: '/blog/interview-with-danyx23/', publishDate: Date {year: 2018, month: 6, day: 28}},
  {url: '/blog/react-notes-1/',          publishDate: Date {year: 2018, month: 3, day: 5}},
  {url: '/blog/learning-platforms-1/'',  publishDate: Date {year: 2017, month: 9, day: 25}}]
```

Now the next one is somehow broken:

```js
let records = await req.db.session.run(`
    MATCH (document :Post)
    RETURN document
    ORDER BY $sort
  `, {
    sort: "document.publishDate DESC",
  })
```

and produces an unsorted or badly sorted result:

```
[ {url: '/blog/datastructures-1/', publishDate: {year: 2017, month: 6, day: 15}},
  {url: '/blog/datastructures-2/', publishDate: {year: 2017, month: 6, day: 20}},
  {url: '/blog/datastructures-3/', publishDate: {year: 2017, month: 6, day: 21}}]
```

And I can't figure out why. It looks like a bug to me or at least something that should be mentioned somewhere.

See, when I mistakenly put a placeholder in the label area:

```
MATCH (document :Post $label)
```

driver warns me:

```
Neo4jError: Parameter maps cannot be used in MATCH patterns 
```

With `$sort`, it just silently does something wrong.

**Comment by lutovich** [comment]
Hi @ivan-kleshnin,

Query parameters can only be used to replace certain parts of the query, like expressions or node ids. Please see [this section of the manual](https://neo4j.com/docs/developer-manual/current/cypher/syntax/parameters/#cypher-parameters-introduction) for more details. They can't be used for labels because Cypher query planner needs to know all the labels in order to plan the query. Also, they can only be used for `ORDER BY` values. In your example value of the `sort` parameter is treated as a constant string instead of property name and `DESC`. So all returned records are sorted by a constant string "document.publishDate DESC" which means they come out in some database-defined order.

Code:

```javascript
let records = await req.db.session.run(`
    MATCH (document :Post)
    RETURN document
    ORDER BY $sort
  `, {
    sort: "document.publishDate DESC",
  })
```

is thus equivalent to:

```javascript
let records = await req.db.session.run(`
    MATCH (document :Post)
    RETURN document
    ORDER BY "document.publishDate DESC"
  `)
```

Sorting records by a constant vaue is technically not an error. Cypher could probably return a warning but user code would need to extract it from the returned `Result` object manually. Warnings do not make queries fail or driver to throw exceptions.

Hope this helps!
