### ISSUE TITLE
Query wont run @1.7.0

### ISSUE THREAD

**Issue by marcopapolo** [neo4j/neo4j-javascript-driver#423]
Hi !
I tried the code below. It works in v1.6.1 and not in v1.7.0
```js
var neo4j = require('neo4j-driver').v1;
const url = 'bolt://hiddenurl.com:12345'
const config = {
    logging: neo4j.logging.console('debug')
  };
var driver = neo4j.driver(
    url, 
    neo4j.auth.basic('user', 'pwd'),
    config
);  

var query = `match(n) return n as node`

var session = driver.session();

session.run(query)
.then(res => {
    res = res.records.map( record => {
        return record.get('node')
    })
    console.log('node found:',res)
    return res
})
.then( () => {
    session.close(() => {
        console.log('we queried the database')
    })
})
.catch( err => console.log(err))
```

Log where it blocks in 1.7.0: 
``` 
1540139801288 DEBUG Connection [0][] created towards hiddenurl.com:12345
1540139801968 DEBUG Connection [0][] negotiated protocol version 3
1540139801970 DEBUG Connection [0][] C: HELLO {user_agent: 'neo4j-javascript/1.7.0', ...}
```

Any ideas where it comes from :) ? 

Cheers !

**Comment by lutovich** [comment]
Hey @marcopapolo,

Which neo4j database version are you using? Is it a single instance or a cluster? How is the database deployed?

**Comment by viz** [comment]
I'm also having problems. Running Neo4j community edition 3.4.5 in grapheneDB and querying from an AWS lambda function.

Simple query works in 1.6.3 but after upgrading to 1.7.0 the transaction just hangs and the lambda function times out (30 second timeout set). No error visible in the logs available on graphene but they are pretty limited.

**Comment by lutovich** [comment]
Hey @viz,

Starting from 1.7.0 driver can speak a new Bolt protocol version 3. This allows it to expose couple new features in the API like transaction timeout and transaction metadata. Protocol versions 1 and 2 are still supported and driver tries to negotiate one of `[3, 2, 1]` with the database after socket connection is established. Database responds with a single protocol version it supports. Neo4j 3.4.5 can never respond to a protocol negotiation request with version 3 because code for version 3 only exists in 3.5 pre-release versions.

Based on this and issue https://github.com/neo4j/neo4j-javascript-driver/issues/406 I assume GrapheneDB has some kind of proxy in front of the database that understands Bolt. This proxy accepts Bolt connections and then connects to the database on behalf of the driver. I think this proxy negotiates Bolt V3 with the driver but then can't handle Bolt V3 initialization message `HELLO`. `HELLO` message has a different structure than `INIT` message in Bolt V1 and V2.

Could you please raise this issue with GrapheneDB?

@marcopapolo are you also experiencing this problem with a GrapheneDB instance?

**Comment by katiepayne** [comment]
I too can verify the 1.7.0 driver has issues connecting to GrapheneDB instances. Using the  v1.6.1 neo4j-driver resolves the issue.

**Comment by lutovich** [comment]
@katiepayne we'd love to help but this issue seems to be on the GrapheneDB side. Driver connects to something that does not correctly handle the negotiated protocol version. Could you please let GrapheneDB know about this problem?

**Comment by viz** [comment]
I've logged a case with GrapheneDB referring to this github issue.

@katiepayne we're using 1.6.3 successfully.

**Comment by viz** [comment]
response from GrapheneDB:

> Yes we’re working on supporting it right now. I will come back to you as soon as we’re there. Please use 1.6 in the meantime.

**Comment by marcopapolo** [comment]
@lutovich yes, same, it is for grapheneDB. @viz thx for the update :)

**Comment by juanjoandres** [comment]
Hi,

Our fix is ready and we're applying it today to our infrastructure. Please reach out to support@graphenedb.com and we'll apply the fix ASAP.

Thanks, @katiepayne! 

@viz Thanks for the heads up here!

**Comment by viz** [comment]
thanks for the quick response @juanjoandres . I've tested one of our services with 1.7.0 and can confirm that it now works properly.

Woohoo!

**Comment by lutovich** [comment]
Thanks, @juanjoandres!
