### ISSUE TITLE
[docs] Guidance on forwards/backwards compatibility w/ neo4j 4.0?

### ISSUE THREAD

**Issue by lmeyerov** [neo4j/neo4j-javascript-driver#525]
We are working through our Neo4j 4 support via the JavaScript bolt driver, and were curious about forwards/backwards compatibility of the node bolt driver:

— backwards: does the node 4.0 bolt driver support Neo4j < 4.0?

— forwards: does the node 1.7.6 bolt support Neo4j 4.x?

(We were not able to tell via the changelog & migration notes)

**Comment by technige** [comment]
@lmeyerov Both scenarios are supported, with caveats.

- The new driver can work with old versions of the server (but may need encryption explicitly enabled)
- The old driver can work with new versions of the server (but may need encryption explicitly disabled)

The encryption changes are due to Neo4j no longer being shipped with a self-signed certificate. Note that older  versions can only be supported in fallback mode (i.e. no new features).

This is described fully in the manual:
https://neo4j.com/docs/driver-manual/current/get-started/#driver-get-started-installation

**Comment by lmeyerov** [comment]
Thank you!
