### ISSUE TITLE
Exports in TypeScript type definition are out of date.

### ISSUE THREAD

**Issue by jharris4** [neo4j/neo4j-javascript-driver#536]
### General Information

**Driver version**: JS driver 4.0.1  

As mentioned in #535 it seems that the TypeScript typings for version 4 of the driver were not updated to reflect the changes from version 1.7.

For example, the types (DateTime etc) are all still on the top level export which they should not.

**Comment by kimroen** [comment]
We ran into this today when updating our driver from 1.x to the latest in the 4.x series. We deployed the change, and got lots of errors saying you cannot call `fromStandardDate` on `undefined`.

The problem as it relates to this issue was that we had imported `DateTime` from `neo4j-driver` directly, and the types made it look like that was perfectly okay. We fixed it by importing `types` instead and getting `DateTime` from that.

**Comment by bigmontz** [comment]
Solved in 4.3
