### ISSUE TITLE
Will this also work for <3.0.0?

### ISSUE THREAD

**Issue by sonukapoor** [neo4j/neo4j-javascript-driver#84]
Hi, 

Will this work over HTTP REST for DB versions < 3.0.0 ?

Thanks

**Comment by legraphista** [comment]
Hey sonukapoor,
This is a driver that implements the new _BOLT_ protocol which was released in Neo4j 3.0.0. 
Unfortunately, if you want to use the REST API, this is not the driver you're looking for.

Best regards,
 Stefan

**Comment by sonukapoor** [comment]
Thanks Stefan. 

We will hopefully upgrade soon to 3.0.0. Quick followup question. Are there any benchmarks or performance tests that were done to compare the REST API vs BOLT?

Sonu

**Comment by legraphista** [comment]
Hi again,

I haven't done any benchmarks, but after the switch to BOLT in production we saw a decrease of ~30% in response time (most likely because of lack of HTTP overhead, connection latency for every request and smaller data size that needs to be transferred between server and database). We also noticed that our maximum throughput has increased dramatically, over 300%.

Stefan

**Comment by sonukapoor** [comment]
Amazing. Thanks a lot.

**Comment by pontusmelke** [comment]
Thanks @legraphista for the nice answers. I will close this issue, if you @sonukapoor have more issues pleas reopen this issue or open a new one.

Regards, 
Pontus
